src/main/java/inscricao/persistence/entity/Idioma.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inscricao.persistence.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Wilson
 */
@Entity
@Table(name = "idioma")
@NamedQueries({
    @NamedQuery(name = "Idioma.findAll", query = "SELECT i FROM Idioma i")})
public class Idioma implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "codigo")
    private Integer codigo;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 30)
    @Column(name = "descricao")
    private String descricao;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idioma")
    private List<Candidato> candidatoList;

    public Idioma() {
    }

    public Idioma(Integer codigo) {
        this.codigo = codigo;
    }

    public Idioma(Integer codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<Candidato> getCandidatoList() {
        return candidatoList;
    }

    public void setCandidatoList(List<Candidato> candidatoList) {
        this.candidatoList = candidatoList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (codigo != null ? codigo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Idioma)) {
            return false;
        }
        Idioma other = (Idioma) object;
        if ((this.codigo == null && other.codigo != null) || (this.codigo != null && !this.codigo.equals(other.codigo))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "inscricao.persistence.entity.Idioma[ codigo=" + codigo + " ]";
    }
    
}

src/main/java/inscricao/faces/mngbeans/InscricaoBean.java
package inscricao.faces.mngbeans;

import inscricao.persistence.entity.Candidato;
import inscricao.persistence.entity.Idioma;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.ejb.TransactionAttribute;
import javax.enterprise.context.SessionScoped;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import utfpr.faces.support.PageBean;
import utfpr.persistence.controller.IdiomaJpaController;
import utfpr.persistence.controller.JpaController;

/**
 *
 * @author Wilson
 */
@Named
@SessionScoped
public class InscricaoBean extends PageBean implements Serializable {
    private Candidato candidato = new Candidato(new Idioma(1)); // inicialmente ingles
    private boolean linkGRUVisivel = false;
    private SimpleDateFormat formatDataVencto = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat formatCompetencia = new SimpleDateFormat("MM/yyyy");
    private boolean informativo;
    private boolean correio;
    private boolean email;

    @Inject
    private IdiomaJpaController idiomaJpaController;
    
    public Candidato getCandidato() {
        return candidato;
    }

    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    @TransactionAttribute
    public List<Idioma> getIdiomas() {
        List<Idioma> idiomas;
        try {
            idiomas = idiomaJpaController.findAll();
        } catch (Exception e) {
            idiomas = new ArrayList<>(0);
            log("Lista de idiomas", e);
        }
        return idiomas;
    }

    public boolean isInformativo() {
        return informativo;
    }

    public void setInformativo(boolean informativo) {
        this.informativo = informativo;
    }

    public boolean isCorreio() {
        return correio;
    }

    public void setCorreio(boolean correio) {
        this.correio = correio;
    }

    public boolean isEmail() {
        return email;
    }

    public void setEmail(boolean email) {
        this.email = email;
    }
    
    public boolean isLinkGRUVisivel() {
        return linkGRUVisivel;
    }
    
    public String getDataVencimento() {
        GregorianCalendar hoje = new GregorianCalendar();
        hoje.add(Calendar.DAY_OF_MONTH, 1);
        return formatDataVencto.format(hoje.getTime());
    }
    
    public String getCompetencia() {
        GregorianCalendar hoje = new GregorianCalendar();
        hoje.add(Calendar.DAY_OF_MONTH, 1);
        return formatCompetencia.format(hoje.getTime());
    }
    
    public void informativoValueChangeListener(ValueChangeEvent event) {
        correio = false;
        email = false;
    }
    
    public void inscricaoAction() {

    }
}

src/main/java/utfpr/faces/support/ApplicationBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;


/**
 * O bean de aplicação
 * @author Wilson
 */
public class ApplicationBean extends FacesBean {
}

src/main/java/utfpr/faces/support/FacesBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpSession;

/**
 * Classe base para os beans de aplicação, sessão, request e página.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class FacesBean implements Serializable {

    private static final Logger logger = Logger.getLogger(PageBean.class.getName());

    /**
     * Retorna o <code>FacesContext</code> corrente.
     * @return O <code>FacesContext</code>
     */
    public FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    /**
     * Retorna o contexto externo de JSF.
     * @return O contexto externo
     */
    public ExternalContext getExternalContext() {
        return getFacesContext().getExternalContext();
    }
    
    /**
     * Retorna ou cria uma sessão. 
     * @param create {@code true} para cria uma nova sessão, caso não exista
     * @return A sessão, ou null, caso não exista
     */
    public HttpSession getSession(boolean create) {
        return (HttpSession) getExternalContext().getSession(create);
    }
    
    /**
     * Retorna a sessão atual ou {@code null} caso não exista.
     * @return A sessão existente ou {@code null}
     */
    public HttpSession getSession() {
        return getSession(false);
    }
    
    /**
     * Retorna o contexto do servlet.
     * @return O contexto do servlet
     */
    public ServletContext getServletContext() {
        return (ServletContext) getExternalContext().getContext();
    }

    /**
     * Gera um log de informação com a mensagem especificada.
     * @param message A mensagem
     */
    public void log(String message) {
        logger.log(Level.INFO, message);
    }

    /**
     * Gera um log de erro com a mensagem e exceção especificadas.
     * @param message A mensagem
     * @param t A exceção
     */
    public void log(String message, Throwable t) {
        logger.log(Level.SEVERE, message, t);
    }
}

src/main/java/utfpr/faces/support/PageBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

/**
 * Classe base dos managed beans de páginas JSF.
 * @author Wilson
 */
public class PageBean extends FacesBean {

    /**
     * Retorna um managed bean dado o seu nome
     * @return O bean de aplicação
     */
    public Object getBean(String name) {
        return getFacesContext().getApplication().evaluateExpressionGet(
            FacesContext.getCurrentInstance(), "#{" + name +  "}", Object.class);
    }

    /**
     * Gera uma mensagem de informação associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void info(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de informação não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void info(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de advertência associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void warn(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de advertência não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void warn(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de erro associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void error(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }

    /**
     * Gera uma mensagem de erro não associada a um componente.
     * @param message <i>summary</i> da mensagem
     */
    public void error(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }
}

src/main/java/utfpr/faces/support/RequestBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

/**
 * Classe base para os beans de request.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class RequestBean extends PageBean {

}

src/main/java/utfpr/faces/support/SessionBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
package utfpr.faces.support;

/**
 * Classe base par o bean de sessão.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class SessionBean extends PageBean {
}

src/main/java/utfpr/persistence/controller/CandidatoJpaController.java
package utfpr.persistence.controller;

/**
 * Desenvolvimento de aplicações Web
 * @author Wilson Horstmeyer Bogado <wilson@utfpr.edu.br>
 */
public class CandidatoJpaController extends JpaController {

    public CandidatoJpaController() {
    }
    
}

src/main/java/utfpr/persistence/controller/IdiomaJpaController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utfpr.persistence.controller;

import inscricao.persistence.entity.Idioma;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

/**
 *
 * @author Wilson
 */
public class IdiomaJpaController extends JpaController {

    @PersistenceContext
    private EntityManager em;

    public IdiomaJpaController() {
    }

    public List<Idioma> findAll() {
        TypedQuery<Idioma> q = em.createQuery(
                "select i from Idioma i order by i.descricao",
                Idioma.class);
        return q.getResultList();
    }
}

src/main/java/utfpr/persistence/controller/JpaController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package utfpr.persistence.controller;

import java.io.Serializable;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class JpaController implements Serializable {

    public JpaController() {
    }

}

src/main/webapp/inscricao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ace="http://www.icefaces.org/icefaces/components"
                template="./WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <style type="text/css">
            .titulo-form {
                font-size: 14pt;
                font-weight: bold;
                margin: 10px 0;
            }
            .iceOutLbl {
                display: inline-block;
                margin-left: 4px;
                width: 50px;
            }
            
            .icePnlGrp {
                margin-top: 4px;
            }
        </style>
    </ui:define>
    
    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <div class="titulo-form">FICHA DE INSCRIÇÃO</div>
            <h:panelGroup style="text-align: left; margin-bottom: 10px;" layout="block">
                <h:outputLabel for="idioma" value="Idioma"/>
                <h:selectOneMenu id="idioma" value="#{inscricaoBean.candidato.idioma.codigo}" style="width:12em" styleClass="ui-selectonemenu">
                    <f:selectItems value="#{inscricaoBean.idiomas}" var="i" itemValue="#{i.codigo}" itemLabel="#{i.descricao}"/>
                </h:selectOneMenu>
                <h:panelGroup layout="block">
                    <h:outputLabel for="cpf" value="CPF"/>
                    <ace:maskedEntry id="cpf" value="#{inscricaoBean.candidato.cpf}"  mask="999999999-99"
                                     label="CPF" size="15" required="true">
                        <f:validator validatorId="CPFValidator"/>
                        <f:converter converterId="CPFConverter"/>
                    </ace:maskedEntry>
                    <h:outputLabel for="rg" value="RG"/>
                    <h:inputText id="rg" value="#{inscricaoBean.candidato.rg}" size="25"
                         styleClass="ui-inputfield" label="RG" maxlength="20" required="true"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="nome" value="Nome"/>
                    <h:inputText id="nome" value="#{inscricaoBean.candidato.nome}" size="50"
                         styleClass="ui-inputfield" label="Nome" maxlength="100" required="true"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="endereco" value="Endereço"/>
                    <h:inputText id="endereco" value="#{inscricaoBean.candidato.endereco}" size="50"
                          styleClass="ui-inputfield" label="Endereço" maxlength="80" required="true"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="cidade" value="Cidade"/>
                    <h:inputText id="cidade" value="#{inscricaoBean.candidato.cidade}" size="50"
                            styleClass="ui-inputfield" label="cidade" maxlength="50" required="true"/>
                    <h:outputLabel for="estado" value="Estado"/>
                    <h:inputText id="estado" value="#{inscricaoBean.candidato.estado}" size="4"
                            styleClass="ui-inputfield" label="Estado" maxlength="2" required="true"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="cep" value="CEP"/>
                    <ace:maskedEntry id="cep" value="#{inscricaoBean.candidato.cep}" mask="99999-999"
                                     label="CEP" size="10" required="true">
                        <f:validator validatorId="CEPValidator"/>
                        <f:converter converterId="CEPConverter"/>
                    </ace:maskedEntry>
                    <h:outputLabel for="bairro" value="Bairro"/>
                    <h:inputText id="bairro" value="#{inscricaoBean.candidato.bairro}" size="30"
                            styleClass="ui-inputfield" label="Bairro" maxlength="50"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="fone" value="Fone"/>
                    <ace:maskedEntry id="fone" value="#{inscricaoBean.candidato.fone}" mask="(99) 9999-9999"
                        label="Fone" size="15"/>
                    <h:outputLabel for="celular" value="Celular"/>
                    <ace:maskedEntry id="celular" value="#{inscricaoBean.candidato.celular}" mask="(99) 9999-9999"
                        label="Celular" size="15"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="email" value="E-mail"/>
                    <h:inputText id="email" value="#{inscricaoBean.candidato.email}" size="80"
                          styleClass="ui-inputfield" label="E-mail" maxlength="200" required="true"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="instituicao" value="Instituição"/>
                    <h:inputText id="instituicao" value="#{inscricaoBean.candidato.instituicao}" size="80"
                          styleClass="ui-inputfield" label="Instituição" maxlength="100" required="true"/>
                </h:panelGroup>
                <h:panelGroup layout="block">
                    <h:outputLabel for="programa" value="Programa"/>
                    <h:inputText id="programa" value="#{inscricaoBean.candidato.programa}" size="80"
                          styleClass="ui-inputfield" label="Programa" maxlength="100" required="true"/>
                </h:panelGroup>
            </h:panelGroup>
            <h:panelGroup layout="block">
                <h:selectBooleanCheckbox id="informativo" value="#{inscricaoBean.informativo}"
                                           valueChangeListener="#{inscricaoBean.informativoValueChangeListener}"/>
                <h:outputLabel for="informativo" value="Receber informativo" style="width: 150px"/>
                <h:selectBooleanCheckbox id="infocorreio" value="#{inscricaoBean.correio}" disabled="#{!inscricaoBean.informativo}"/>
                <h:outputLabel for="infocorreio" value="correio" style="width: 100px"/>
                <h:selectBooleanCheckbox id="infoemail" value="#{inscricaoBean.email}" disabled="#{!inscricaoBean.informativo}"/>
                <h:outputLabel for="infoemail" value="e-mail" style="width: 100px"/>
            </h:panelGroup>
            <h:commandButton value="Confirmar Inscrição" action="#{inscricaoBean.inscricaoAction}" style="margin-top: 1em"/>
            <h:panelGroup layout="block">
                <h:outputLink value="http://consulta.tesouro.fazenda.gov.br/gru/gerarHTML.asp" target="_blank" rendered="#{inscricaoBean.linkGRUVisivel}">
                    <h:outputText value="Gerar GRU para Pagamento"/>
                    <f:param name="codigo_favorecido" value="154358"/>
                    <f:param name="gestao" value="15246"/>
                    <f:param name="codigo_correlacao" value="1213"/>
                    <f:param name="nome_favorecido" value="UTFPR - CAMPUS CURITIBA"/>
                    <f:param name="codigo_recolhimento" value="28832-2"/>
                    <f:param name="nome_recolhimento" value="DALEM"/>
                    <f:param name="referencia" value="24000000000000000000"/>
                    <f:param name="competencia" value="#{inscricaoBean.competencia}"/>
                    <f:param name="vencimento" value="#{inscricaoBean.dataVencimento}"/>
                    <f:param name="boleto" value="3"/>
                    <f:param name="impressao" value="sa"/>
                    <f:param name="campo" value="nrcr"/>
                    <f:param name="ind" value="0"/>
                    <f:param name="valorPrincipal" value="100,00"/>
                    <f:param name="valorTotal" value="100,00"/>
                    <f:param name="cnpj_cpf" value="#{inscricaoBean.candidato.cpf}"/>
                </h:outputLink>
            </h:panelGroup>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:comps="http://xmlns.jcp.org/jsf/composite/util"
                template="./WEB-INF/templates/layout.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="metadata"/>
    <ui:define name="styles"/>
    <ui:define name="javascript"/>

    <ui:define name="content">
        <h:form>
            <comps:login usuario="" senha="" layoutVertical="false"/><br/>
            <h:commandButton value="Entrar"/>
        </h:form>
    </ui:define>

</ui:composition>